name: flocse_core
description: A starting point for Dart libraries or applications.
resolution: workspace
version: 0.1.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.9.0

# Add regular dependencies here.
dependencies:
  meta: ^1.16.0

dev_dependencies:
  lints: ^6.0.0
  test: ^1.25.6
  mocktail: ^0.3.0
