name: flocse
description: An attempt at component/event based programming with flutter
version: 1.0.0
homepage: "https://github.com/FlutterJoey"
repository: "https://github.com/FlutterJoey/flocse"

environment:
  sdk: ">=2.15.1 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter:
