name: flocse
description: An attempt at component/event based programming with flutter
version: 2.2.0
resolution: workspace
homepage: "https://github.com/FlutterJoey"
repository: "https://github.com/FlutterJoey/flocse"

environment:
  sdk: ">=3.5.0 <4.0.0"
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1
  mocktail: ^0.3.0

flutter:
